server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_center
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true